### ISSUE TITLE
Wrong written Colebrook formula in Manual (26/08/2020)

### ISSUE THREAD

**Issue by noriegaedu** [EdM44/hydraulics#1]
Hi, at page 3 of the package Manual from August 26, 2020 it says:

![image](https://user-images.githubusercontent.com/29818621/98323703-d86aec80-1fc0-11eb-92b2-a0bbcace0d43.png)

There is an extra `D [Diameter]` in the denominator of first term inside the log function. I thought you should know it.

**Comment by EdM44** [comment]
Thank you for catching that, Eduardo. The same error appears in the vignette. I will correct them on my next revision.
